version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: campeonato_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - campeonato_net
    restart: unless-stopped

  app:
    build: .
    container_name: campeonato_app
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - PORT=${PORT}
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - campeonato_net
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mysql_data:

networks:
  campeonato_net:
    driver: bridge